---
- name: Install GPG
  tags: nodejs
  apt:
    name: gnupg
    update_cache: true
    state: present

- name: Install the gpg key for nodejs LTS
  apt_key:
    url: "https://deb.nodesource.com/gpgkey/nodesource.gpg.key"
    state: present

- name: Install the nodejs LTS repos
  apt_repository:
    repo: "deb https://deb.nodesource.com/node_{{ NODEJS_VERSION }}.x {{ ansible_distribution_release }} main"
    state: present
    update_cache: true

- name: Install NodeJS
  tags: nodesjs
  apt:
    name: nodejs
    state: latest

# newline character added at the end of the file
